### ISSUE TITLE
Jitsi Meet

### ISSUE THREAD

**Issue by ovari** [HMarzban/ep_wrtc_heading#3]
Is this reusing code from [Jitsi](https://jitsi.org/) and [Jitsi Meet](https://meet.jit.si/)? Thank you

**Comment by HMarzban** [comment]
No, it's based on native browser API and [WebRTC](https://en.m.wikipedia.org/wiki/WebRTC) concept.
We've developed it from scratch.

**Comment by ovari** [comment]
Thank you
